### ISSUE TITLE
composer file missing org name and needs to be lower case

### ISSUE THREAD

**Issue by greggreenhaw** [OneSignal/onesignal-php-api#5]
### What happened?

can not install with composer 2

### Steps to reproduce?

```Markdown
can not install with composer 2
```

### What did you expect to happen?

install directions do not work

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kesheshyan** [comment]
Hey @greggreenhaw, thanks for reporting. Currently we are not able to publish our package to composer because someone took ownership of OneSignal organization and we cannot use onesignal/ namespace. We are trying to reach the owner and transfer the ownership. Meanwhile you can try downloading this repo and use an *autoload* section in your composer.json file like this:
```json
"autoload": {
        "psr-4": { "onesignal\\client\\" : "path_to_library/lib/" }
    }
```

**Comment by kesheshyan** [comment]
Hey @greggreenhaw, thanks for your patience! https://packagist.org/packages/onesignal/onesignal-php-api
